#!D:\TCD\Term2\applied-statistics\main\my_env\Scripts\python.exe
from __future__ import division, print_function, absolute_import
import os
import sys

sys.path = [os.path.join(os.path.abspath(os.path.dirname(__file__)), "..")] + sys.path

from deepdish.io.ls import main

if __name__ == '__main__':
    main()
